CXX = c++

CXXFLAGS = -Wall -Wextra -Werror -std=c++98

NAME = bsp

SRCS = bsp.cpp Fixed.cpp main.cpp Point.cpp

HEADERS = Fixed.hpp Point.hpp

OBJS = $(SRCS:.cpp=.o)

all: $(NAME)

%.o: %.cpp $(HEADERS)
	$(CXX) $(CXXFLAGS) -c $< -o $@

$(NAME): $(OBJS) $(HEADERS)
	$(CXX) $(CXXFLAGS) $(OBJS) -o $(NAME)

clean:
	rm -f $(OBJS)

fclean: clean
	rm -f $(NAME)

re: fclean all

run: all
	./$(NAME)

.PHONY: all clean fclean re
